# Generated by Django 5.1.15 on 2026-09-24 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failed', 'Connexion échouée'), ('logout', 'Déconnexion'), ('password_changed', 'Mot de passe changé'), ('password_reset_requested', 'Réinitialisation demandée'), ('password_reset_confirmed', 'Réinitialisation confirmée'), ('user_created', 'Compte créé'), ('user_updated', 'Compte modifié (rôle/statut)')], db_index=True, max_length=32)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('target_user_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text="Qui a déclenché l'action. Null si non authentifié (ex. tentative de login échouée).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text="Compte visé par l'action, si différent de l'acteur (ex. admin modifiant un tiers).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entrée du journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
