# Generated by Django 5.1.15 on 2026-09-28 16:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failed', 'Connexion échouée'), ('logout', 'Déconnexion'), ('password_changed', 'Mot de passe changé'), ('password_reset_requested', 'Réinitialisation demandée'), ('password_reset_confirmed', 'Réinitialisation confirmée'), ('user_created', 'Compte créé'), ('user_updated', 'Compte modifié (rôle/statut)'), ('user_deleted', 'Compte supprimé définitivement'), ('patient_created', 'Dossier patient créé'), ('patient_updated', 'Dossier patient modifié'), ('patient_archived', 'Dossier patient archivé'), ('patient_reactivated', 'Dossier patient réactivé'), ('patient_deleted', 'Dossier patient supprimé définitivement'), ('patient_viewed', 'Dossier patient consulté'), ('patient_list_viewed', 'Liste des patients consultée')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
