# Generated by Django 5.1.15 on 2026-10-05 08:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_alter_antecedentsfamiliaux_fratrie_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_consultation', models.CharField(choices=[('premiere', 'Première consultation'), ('suivi', 'Consultation de suivi'), ('urgence', "Consultation d'urgence"), ('telemedecine', 'Télémédecine'), ('pre_operatoire', 'Consultation pré-opératoire'), ('autre', 'Autre')], default='premiere', max_length=20, verbose_name='type de consultation')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=10, verbose_name='statut')),
                ('motif', models.TextField(verbose_name='motif principal')),
                ('grossesse_en_cours', models.BooleanField(default=False, verbose_name='grossesse en cours')),
                ('grossesse_trimestre', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='trimestre de grossesse')),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='poids (kg)')),
                ('taille_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='taille (cm)')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)], verbose_name='température (°C)')),
                ('frequence_cardiaque', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)], verbose_name='fréquence cardiaque (bpm)')),
                ('pression_arterielle_systolique', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)], verbose_name='pression artérielle systolique (mmHg)')),
                ('pression_arterielle_diastolique', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='pression artérielle diastolique (mmHg)')),
                ('frequence_respiratoire', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='fréquence respiratoire (/min)')),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='SpO₂ (%)')),
                ('glycemie_capillaire', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(600)], verbose_name='glycémie capillaire')),
                ('diurese', models.CharField(blank=True, max_length=100, verbose_name='diurèse')),
                ('symptomes', models.JSONField(blank=True, default=list, verbose_name='symptômes')),
                ('autres_symptomes', models.TextField(blank=True, verbose_name='autres symptômes')),
                ('antecedents_mentionnes', models.JSONField(blank=True, default=list, verbose_name='antécédents personnels & mode de vie')),
                ('tabac', models.CharField(blank=True, choices=[('non', 'Non'), ('sevre', 'Sevré'), ('actif', 'Actif')], max_length=10, verbose_name='tabac')),
                ('alcool', models.CharField(blank=True, choices=[('non', 'Non'), ('occasionnel', 'Occasionnel'), ('regulier', 'Régulier')], max_length=12, verbose_name='alcool')),
                ('allergies_signalees', models.BooleanField(default=False, verbose_name='allergies signalées')),
                ('allergies_detail', models.TextField(blank=True, verbose_name='détail des allergies')),
                ('hypothese_diagnostique', models.TextField(blank=True, verbose_name='hypothèse diagnostique')),
                ('traitements_en_cours', models.JSONField(blank=True, default=list, verbose_name='traitements en cours')),
                ('observations', models.TextField(blank=True, verbose_name='observations / notes cliniques')),
                ('recommandation', models.TextField(blank=True, verbose_name='recommandation')),
                ('commentaire_medecin', models.TextField(blank=True, verbose_name='commentaire du médecin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('medecin', models.ForeignKey(blank=True, help_text='Médecin ayant réalisé la consultation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicament', models.CharField(max_length=200, verbose_name='médicament')),
                ('posologie', models.CharField(blank=True, max_length=200, verbose_name='posologie')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='durée du traitement')),
                ('quantite', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='quantité')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'ligne de prescription',
                'verbose_name_plural': 'lignes de prescription',
            },
        ),
        migrations.CreateModel(
            name='RendezVousSuivi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_rdv', models.DateField(verbose_name='date du rendez-vous')),
                ('heure_rdv', models.TimeField(blank=True, null=True, verbose_name='heure du rendez-vous')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_suivi', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'rendez-vous de suivi',
                'verbose_name_plural': 'rendez-vous de suivi',
                'ordering': ['date_rdv', 'heure_rdv'],
            },
        ),
    ]
