# Generated by Django 5.1.15 on 2026-10-05 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('clinique', 'Services cliniques'), ('fonctionnel', 'Services fonctionnels (plateaux techniques)'), ('support', 'Services de support'), ('transversal', 'Services transversaux')], max_length=20, verbose_name='catégorie')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='nom')),
                ('role_principal', models.TextField(blank=True, verbose_name='rôle principal')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin_oriente',
            field=models.ForeignKey(blank=True, help_text="Médecin vers lequel le patient est orienté à l'admission (distinct de `medecin`, l'auteur).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_orientees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='motif_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='catégories de motif'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='numero_couverture',
            field=models.CharField(blank=True, max_length=100, verbose_name='n° de couverture (CMU / mutuelle)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='type_couverture',
            field=models.CharField(choices=[('aucune', 'Aucune — patient payant'), ('cmu', 'CMU'), ('mutuelle', 'Mutuelle / assurance privée')], default='aucune', max_length=10, verbose_name='type de couverture'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='urgence',
            field=models.BooleanField(default=False, verbose_name='statut urgent'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='services_orientation',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='consultations.service', verbose_name="services d'orientation"),
        ),
    ]
