# Generated by Django 5.1.15 on 2026-10-05 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_seed_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('texte', models.TextField(blank=True, verbose_name='texte du conseil')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils_patient', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'conseil au patient',
                'verbose_name_plural': 'conseils au patient',
            },
        ),
    ]
