# Generated by Django 5.1.15 on 2026-09-28 14:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_dossier', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro de dossier')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('sexe', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10, verbose_name='sexe')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('cni', models.CharField(blank=True, max_length=30, verbose_name='numéro CNI')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='nationalité')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='commune')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='quartier')),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='groupe sanguin')),
                ('taille_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='taille (cm)')),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='poids (kg)')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('antecedents', models.TextField(blank=True, verbose_name='antécédents médicaux')),
                ('traitements_en_cours', models.TextField(blank=True, verbose_name='traitements en cours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membre du personnel clinique ayant créé le dossier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
