# Generated by Django 5.1.15 on 2026-09-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentsFamiliaux',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='antecedents_familiaux', serialize=False, to='patients.patient')),
                ('pere_numero_dossier', models.CharField(blank=True, max_length=20, verbose_name='numéro de dossier du père')),
                ('pere_vivant', models.BooleanField(blank=True, null=True, verbose_name='père vivant')),
                ('pere_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='âge du père')),
                ('pere_diabetique', models.BooleanField(blank=True, null=True, verbose_name='père diabétique')),
                ('pere_pathologies', models.JSONField(blank=True, default=list, verbose_name='autres pathologies du père')),
                ('mere_numero_dossier', models.CharField(blank=True, max_length=20, verbose_name='numéro de dossier de la mère')),
                ('mere_vivante', models.BooleanField(blank=True, null=True, verbose_name='mère vivante')),
                ('mere_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='âge de la mère')),
                ('mere_diabetique', models.BooleanField(blank=True, null=True, verbose_name='mère diabétique')),
                ('mere_pathologies', models.JSONField(blank=True, default=list, verbose_name='autres pathologies de la mère')),
                ('fratrie_telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone du frère/de la sœur')),
                ('fratrie_numero_dossier', models.CharField(blank=True, max_length=20, verbose_name='numéro de dossier du frère/de la sœur')),
                ('fratrie_vivant', models.BooleanField(blank=True, null=True, verbose_name='frère/sœur vivant(e)')),
                ('fratrie_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='âge du frère/de la sœur')),
                ('fratrie_cancer', models.BooleanField(blank=True, null=True, verbose_name='frère/sœur atteint(e) de cancer')),
                ('fratrie_diabetique', models.BooleanField(blank=True, null=True, verbose_name='frère/sœur diabétique')),
                ('fratrie_drepanocytose', models.BooleanField(blank=True, null=True, verbose_name='frère/sœur drépanocytaire')),
                ('autres_antecedents_familiaux', models.BooleanField(default=False, verbose_name='autres antécédents familiaux connus')),
            ],
            options={
                'verbose_name': 'antécédents familiaux',
                'verbose_name_plural': 'antécédents familiaux',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='a_contact_urgence_associe',
            field=models.BooleanField(default=False, verbose_name="contact d'urgence associé"),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedents_chirurgicaux',
            field=models.TextField(blank=True, verbose_name='antécédents chirurgicaux'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence',
            field=models.CharField(blank=True, help_text='Nom et téléphone, ex. Awa KOFFI — 07 00 00 00 00', max_length=255, verbose_name="contact d'urgence"),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nombre_enfants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='patient',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, verbose_name='situation matrimoniale'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='antecedents',
            field=models.TextField(blank=True, verbose_name='antécédents personnels'),
        ),
    ]
