# Generated by Django 5.1.15 on 2026-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_antecedentsfamiliaux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_urgence',
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_lien',
            field=models.CharField(blank=True, choices=[('conjoint', 'Conjoint(e)'), ('parent', 'Parent'), ('enfant', 'Enfant'), ('fratrie', 'Frère/Sœur'), ('ami', 'Ami(e)'), ('autre', 'Autre')], max_length=20, verbose_name="lien de parenté du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name="nom du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name="téléphone du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Archivage réversible d'un dossier créé par erreur ou obsolète — préférer à la suppression.", verbose_name='dossier actif'),
        ),
    ]
