# Generated by Django 5.1.15 on 2026-09-28 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_contact_urgence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentsfamiliaux',
            name='fratrie_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='âge du frère/de la sœur'),
        ),
        migrations.AlterField(
            model_name='antecedentsfamiliaux',
            name='mere_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='âge de la mère'),
        ),
        migrations.AlterField(
            model_name='antecedentsfamiliaux',
            name='pere_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='âge du père'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nombre_enfants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name="nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='poids_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='poids (kg)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='taille_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='taille (cm)'),
        ),
    ]
