# Generated by Django 5.1.15 on 2026-09-24 13:24

from django.db import migrations, models

RENAMES = {
    "admin_national": "super_admin",
    "admin_regional": "admin",
}


def rename_roles_forward(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for old_value, new_value in RENAMES.items():
        User.objects.filter(role=old_value).update(role=new_value)


def rename_roles_backward(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for old_value, new_value in RENAMES.items():
        User.objects.filter(role=new_value).update(role=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('biologiste', 'Biologiste'), ('medecin', 'Médecin'), ('super_admin', 'Super administrateur'), ('admin', 'Administrateur'), ('analyste', 'Analyste')], max_length=32, verbose_name='rôle'),
        ),
        migrations.RunPython(rename_roles_forward, rename_roles_backward),
    ]
