# Generated by Django 5.1.15 on 2026-10-08 14:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0004_conseilpatient'),
        ('patients', '0004_alter_antecedentsfamiliaux_fratrie_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('categorie', models.CharField(choices=[('metabolisme', 'Métabolisme'), ('renal', 'Rénal'), ('hepatique', 'Hépatique'), ('inflammation', 'Inflammation'), ('hematologie', 'Hématologie'), ('endocrinologie', 'Endocrinologie'), ('cardiologie', 'Cardiologie'), ('vitamines_mineraux', 'Vitamines & minéraux'), ('infectiologie_serologie', 'Infectiologie / Sérologie'), ('gynecologie_cytologie', 'Gynécologie / Cytologie'), ('coagulation', 'Coagulation'), ('marqueurs_tumoraux', 'Marqueurs tumoraux'), ('hormonal_fertilite', 'Hormonal / Fertilité'), ('immunologie_allergie', 'Immunologie / Allergie'), ('parasitologie_microbiologie', 'Parasitologie / Microbiologie'), ('toxicologie', 'Toxicologie'), ('bilan_prenatal_grossesse', 'Bilan prénatal / Grossesse')], max_length=30, verbose_name='catégorie')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='unité')),
                ('taux_cmu', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='taux de couverture CMU (%)')),
                ('prix_fcfa', models.PositiveIntegerField(verbose_name='prix (FCFA)')),
                ('duree_estimee', models.CharField(blank=True, max_length=20, verbose_name='délai de rendu estimé')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'examen (référentiel)',
                'verbose_name_plural': 'examens (référentiel)',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_demande', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro de demande')),
                ('statut', models.CharField(choices=[('saisie', 'En cours de traitement'), ('validation', 'En validation'), ('valide', 'Terminé'), ('urgent', 'Cas urgent signalé'), ('recommande', 'Recommandé par médecin'), ('rejete', 'Échantillon rejeté — nouveau prélèvement requis')], default='saisie', max_length=12, verbose_name='statut')),
                ('urgent', models.BooleanField(default=False, verbose_name='urgent')),
                ('motif', models.TextField(blank=True, verbose_name='motif / note pour le laboratoire')),
                ('type_couverture', models.CharField(choices=[('aucune', 'Aucune — patient payant'), ('cmu', 'CMU'), ('mutuelle', 'Mutuelle / assurance privée')], default='aucune', max_length=10, verbose_name='type de couverture')),
                ('numero_couverture', models.CharField(blank=True, max_length=100, verbose_name='n° de couverture (CMU / mutuelle)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile', 'Mobile Money'), ('carte', 'Carte bancaire'), ('cheque', 'Chèque'), ('autre', 'Autre')], default='especes', max_length=10, verbose_name='mode de paiement')),
                ('montant_fcfa', models.PositiveIntegerField(default=0, editable=False, help_text='Calculé côté serveur à partir du prix catalogue des examens liés — jamais fourni par le client.', verbose_name='montant (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('consultation', models.ForeignKey(blank=True, help_text="Consultation d'origine, si la demande est rattachée à une consultation médicale.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_examens', to='consultations.consultation')),
                ('cree_par', models.ForeignKey(blank=True, help_text='Médecin ou biologiste ayant enregistré la demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_examens_creees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_examens', to='patients.patient')),
            ],
            options={
                'verbose_name': "prescription d'examen",
                'verbose_name_plural': "prescriptions d'examens",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamenPrescrit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='prescriptions.examen')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_prescrits', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': "ligne d'examen prescrit",
                'verbose_name_plural': "lignes d'examen prescrit",
                'constraints': [models.UniqueConstraint(fields=('prescription', 'examen'), name='unique_examen_par_prescription')],
            },
        ),
    ]
